Repository bcgov/hsb-dashboard, pull requests merged in 2024-02, with the labels that each got.

#72 HOSTSD-257, 256 - loading ui for dashboard, admin pages
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/client/dashboard/page.tsx
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/app/page.tsx
  src/dashboard/src/components/adminLoadingAnimation/AdminLoadingAnimation.module.scss
  src/dashboard/src/components/adminLoadingAnimation/AdminLoadingAnimation.tsx
  src/dashboard/src/components/adminLoadingAnimation/index.ts
  src/dashboard/src/components/charts/loadingAnimation/LoadingAnimation.module.scss
  src/dashboard/src/components/index.ts
  src/dashboard/src/components/pageLoadingAnimation/PageLoadingAnimation.module.scss
  src/dashboard/src/components/pageLoadingAnimation/PageLoadingAnimation.tsx
  src/dashboard/src/components/pageLoadingAnimation/index.ts
Labels: enhancement

#73 HOSTSD-266 Fix dashboard
  src/dashboard/src/app/api/utils/dispatch.ts
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/index.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/useAllOrganizationsDoughnutChart.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/utils/generateAllOrganizationsDoughnutChart.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/utils/generateDoughnutChart.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/utils/index.ts
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
  src/dashboard/src/components/filter/FilteredOrganizations.tsx
  src/dashboard/src/components/filter/FilteredServerItems.tsx
  src/dashboard/src/components/filter/FilteredTenants.tsx
  src/dashboard/src/components/header/Message.tsx
  src/dashboard/src/hooks/filter/useFilteredOperatingSystemItems.ts
  src/dashboard/src/store/useFilteredStore.ts
Labels: bug

#74 HOSTSD-266 Fix dashboard filter
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/components/filter/Filter.tsx
Labels: bug

#75 HOSTSD-244 Update admin loading
  src/dashboard/src/app/client/admin/users/ClientAdmin.module.scss
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/client/admin/users/utils/searchUsers.ts
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/users/IUserForm.ts
  src/dashboard/src/app/hsb/admin/users/Users.module.scss
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/app/page.tsx
  src/dashboard/src/components/admin/index.ts
  src/dashboard/src/components/admin/users/IUserForm.ts
  src/dashboard/src/components/admin/users/index.ts
  src/dashboard/src/components/admin/users/user-dialog/UserDialog.module.scss
  src/dashboard/src/components/admin/users/user-dialog/UserDialog.tsx
  src/dashboard/src/components/admin/users/user-dialog/index.ts
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
  src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.tsx
  src/dashboard/src/components/charts/index.ts
  src/dashboard/src/components/charts/line/LineChart.tsx
  src/dashboard/src/components/charts/loadingAnimation/LoadingAnimation.tsx
  src/dashboard/src/components/forms/interfaces/IFormRecord.ts
  src/dashboard/src/components/index.ts
  src/dashboard/src/components/loadingAnimation/LoadingAnimation.module.scss
  src/dashboard/src/components/loadingAnimation/LoadingAnimation.tsx
  src/dashboard/src/components/loadingAnimation/index.ts
  src/dashboard/src/components/table/ITableHeaderProps.ts
  src/dashboard/src/components/table/ITableRowProps.ts
  src/dashboard/src/components/table/Table.module.scss
  src/dashboard/src/components/table/Table.tsx
Labels: bug, enhancement

#76 HOSTSD-248 Update github actions
  .github/workflows/ci-cd-dev.yml
  .github/workflows/dotnet.yml
  .github/workflows/nextjs.yml
Labels: enhancement

#78 HOSTSD-266 Fix dashboard filter
  devops/kustomize/base/tekton/imageStreams/kustomization.yaml
  devops/kustomize/base/tekton/pipelines/kustomization.yaml
  devops/kustomize/base/tekton/service-account/kustomization.yaml
  devops/kustomize/base/tekton/service-account/role-binding.yaml
  devops/kustomize/base/tekton/service-account/role.yaml
  devops/kustomize/base/tekton/tasks/kustomization.yaml
  devops/kustomize/cluster/kustomization.yaml
  devops/kustomize/overlays/dev/kustomization.yaml
  devops/kustomize/overlays/test/kustomization.yaml
  devops/kustomize/overlays/tools/kustomization.yaml
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
  src/dashboard/src/components/filter/FilteredOrganizations.tsx
  src/dashboard/src/components/filter/FilteredServerItems.tsx
  src/dashboard/src/components/filter/FilteredTenants.tsx
  src/dashboard/src/store/useFilteredStore.ts
Labels: bug, enhancement

#79 HOSTSD-147 Test CI/CD
  devops/kustomize/base/tekton/image-streams/api.yaml
  devops/kustomize/base/tekton/image-streams/app.yaml
  devops/kustomize/base/tekton/image-streams/db-migration.yaml
  devops/kustomize/base/tekton/image-streams/kustomization.yaml
  devops/kustomize/base/tekton/roles/role-bind.yaml
  devops/kustomize/base/tekton/roles/role.yaml
  devops/kustomize/overlays/tools/kustomization.yaml
Labels: enhancement

#80 HOSTSD-272 - Optimize UI for smaller screens
  src/dashboard/src/app/login/Login.module.scss
  src/dashboard/src/components/charts/bar/allocationByVolume/AllocationByVolume.tsx
  src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.module.scss
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
  src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.module.scss
  src/dashboard/src/components/charts/line/LineChart.module.scss
  src/dashboard/src/components/filter/Filter.module.scss
  src/dashboard/src/components/pageLoadingAnimation/PageLoadingAnimation.module.scss
  src/dashboard/src/styles/_variables.scss
  src/dashboard/src/styles/globals.scss
Labels: enhancement

#81 HOSTSD-226 Add confirmation popup
  .github/workflows/ci-cd-dev.yml
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/users/[id]/page.tsx
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/components/confirmPopup/ConfirmLink.tsx
  src/dashboard/src/components/confirmPopup/ConfirmPopup.module.scss
  src/dashboard/src/components/confirmPopup/ConfirmPopup.tsx
  src/dashboard/src/components/confirmPopup/index.ts
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/components/header/Header.tsx
  src/dashboard/src/store/index.ts
  src/dashboard/src/store/useNavigateStore.ts
Labels: enhancement

#82 HOSTSD-273 Fix total formula
  devops/kustomize/base/data-service/cron-job.yaml
  src/api/Areas/Dashboard/Controllers/ServerItemController.cs
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
  src/dashboard/src/components/filter/FilteredOrganizations.tsx
  src/dashboard/src/components/filter/FilteredServerItems.tsx
  src/dashboard/src/components/filter/FilteredTenants.tsx
  src/dashboard/src/hooks/data/useOperatingSystemItems.ts
  src/data-service/DataService.cs
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/OrganizationService.cs
  src/libs/dal/Services/ServerItemService.cs
Labels: bug, enhancement

#83 HOSTSD-273 Fixing bugs
  devops/kustomize/base/api/deploy.yaml
  devops/kustomize/overlays/dev/api/kustomization.yaml
  devops/kustomize/overlays/test/api/kustomization.yaml
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
  src/dashboard/src/components/filter/FilteredOrganizations.tsx
  src/dashboard/src/components/filter/FilteredTenants.tsx
Labels: bug

#84 HOSTSD-277 Fix refresh token
  devops/kustomize/base/app/deploy.yaml
  src/api/Dockerfile
Labels: bug

#85 HOSTSD-273 Fix dashboard
  src/dashboard/src/components/dashboard/Dashboard.tsx
Labels: bug

#86 HOSTSD-288 - UI: add new users for hsb/admin/users page
  src/dashboard/src/app/hsb/admin/users/Users.module.scss
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/components/table/ITableAddNewProps.ts
  src/dashboard/src/components/table/Table.module.scss
  src/dashboard/src/components/table/Table.tsx
Labels: enhancement

#87 HOSTSD-246 Fix data
  src/api/Areas/Admin/Controllers/UserController.cs
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/page.tsx
  src/dashboard/src/components/charts/allocationTable/TableRow.tsx
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/BarChart.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/useStorageTrendsData.ts
  src/dashboard/src/components/charts/bar/smallBar/BarRow.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/utils/generateDoughnutChart.ts
  src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.tsx
  src/dashboard/src/components/charts/doughnut/totalStorage/hooks/generateDoughnutChart.ts
  src/dashboard/src/components/charts/storageTrends/useStorageTrendsData.ts
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/utils/convertToStorageSize.ts
  src/libs/dal/HSB.DAL.csproj
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/UserService.cs
Labels: bug

#89 HOSTSD-292 Fix Organization Admin
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/filter/Filter.tsx
Labels: bug

#90 No ticket - Adding back date picker buttons after hiding export to excel buttons
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.module.scss
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.module.scss
Labels: bug

#91 HOSTSD-275 Fix dashboard
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/dashboard/Dashboard.tsx
Labels: bug

#92 HOSTSD-275 Fix dashboard
  src/dashboard/src/components/dashboard/Dashboard.tsx
Labels: bug

#93 HOSTSD-278 - Allocation Table - showing filtered list while searching
  src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
Labels: enhancement

#94 HOSTSD-299 - UI: Filter Dropdown
  src/dashboard/src/app/style-guide/page.tsx
  src/dashboard/src/components/filter/Filter.module.scss
  src/dashboard/src/components/forms/select/FilterDropdown.tsx
  src/dashboard/src/components/forms/select/Select.module.scss
  src/dashboard/src/components/forms/select/index.ts
Labels: enhancement

#98 HOSTSD-259 - Adding breadcrumbs under filter
  src/dashboard/public/images/dashboard-icon.png
  src/dashboard/public/images/server-icon.png
  src/dashboard/src/components/breadcrumbs/Breadcrumbs.module.scss
  src/dashboard/src/components/breadcrumbs/Breadcrumbs.tsx
  src/dashboard/src/components/breadcrumbs/index.ts
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.module.scss
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/header/Header.module.scss
  src/dashboard/src/components/header/Header.tsx
  src/dashboard/src/components/index.ts
Labels: enhancement

#99 Fix Data Service & Add New User
  src/api/Areas/Admin/Controllers/TenantController.cs
  src/api/Areas/Admin/Controllers/UserController.cs
  src/api/Keycloak/CssHelper.cs
  src/dashboard/package-lock.json
  src/dashboard/package.json
  src/dashboard/src/app/api/admin/users/route.ts
  src/dashboard/src/app/api/auth/authOptions.ts
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/users/AddNewUserRow.tsx
  src/dashboard/src/app/hsb/admin/users/EditUserRow.tsx
  src/dashboard/src/app/hsb/admin/users/Users.module.scss
  src/dashboard/src/app/hsb/admin/users/defaultUser.ts
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/hsb/admin/users/validateUser.tsx
  src/dashboard/src/app/layout.tsx
  src/dashboard/src/components/auth/AuthState.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/forms/text/Text.module.scss
  src/dashboard/src/components/forms/text/Text.tsx
  src/dashboard/src/components/table/ITableRowProps.ts
  src/dashboard/src/components/table/Table.tsx
  src/dashboard/src/hooks/api/admin/useApiGroups.ts
  src/dashboard/src/hooks/api/admin/useApiOrganizations.ts
  src/dashboard/src/hooks/api/admin/useApiTenants.ts
  src/dashboard/src/hooks/api/admin/useApiUsers.ts
  src/dashboard/src/hooks/data/useGroups.ts
  src/dashboard/src/hooks/data/useOperatingSystemItems.ts
  src/dashboard/src/hooks/data/useOrganizations.ts
  src/dashboard/src/hooks/data/useRoles.ts
  src/dashboard/src/hooks/data/useServerItems.ts
  src/dashboard/src/hooks/data/useTenants.ts
  src/dashboard/src/hooks/data/useUsers.ts
  src/dashboard/src/utils/dispatch.ts
  src/dashboard/src/utils/index.ts
  src/dashboard/src/utils/keycloakSessionLogOut.ts
  src/dashboard/src/utils/validateEmail.ts
  src/data-service/DataService.cs
  src/data-service/Helpers/HsbApiService.cs
  src/data-service/Helpers/IHsbApiService.cs
Labels: bug, enhancement

#100 HOSTSD-271 - Updating Breadcrumbs and adding totals to server charts
  src/dashboard/src/components/breadcrumbs/Breadcrumbs.tsx
  src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.module.scss
  src/dashboard/src/components/header/Message.tsx
Labels: enhancement

#101 HOSTSD-246 Update Data Service
  src/api/Areas/Services/Controllers/FileSystemItemController.cs
  src/api/Areas/Services/Controllers/ServerItemController.cs
  src/data-service/Config/ServiceOptions.cs
  src/data-service/DataService.cs
  src/data-service/Helpers/HsbApiService.cs
  src/data-service/Helpers/IHsbApiService.cs
  src/data-service/Helpers/ServiceNowApiService.cs
  src/data-service/appsettings.json
  src/libs/dal/Migrations/1.0.2/Up/PostUp/00-Cleanup.sql
  src/libs/dal/Migrations/1.0.2/Up/PostUp/00-DataSync.sql
  src/libs/dal/Migrations/20240229014422_1.0.2.Designer.cs
  src/libs/dal/Migrations/20240229014422_1.0.2.cs
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/IFileSystemItemService.cs
  src/libs/dal/Services/IServerItemService.cs
  src/libs/dal/Services/ServerItemService.cs
Labels: bug, enhancement
