Repository bcgov/hsb-dashboard, pull requests merged in 2024-03, with the labels that each got.

#102 HOSTSD-271 - Adding total used to server chart
  src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/allocationTable/TableRow.tsx
Labels: enhancement

#104 HOSTSD-246 Fix Data Service
  README.md
  scripts/help.sh
  src/data-service/DataService.cs
Labels: bug, enhancement

#105 HOSTSD-306 Documentation
  EMERALD.md
  README.md
  devops/kustomize/base/tekton/tasks/data-service.yaml
Labels: documentation

#106 HOSTSD-302 - Admin: add ability to remove 'add new user' rows
  src/dashboard/src/app/hsb/admin/users/AddNewUserRow.tsx
  src/dashboard/src/app/hsb/admin/users/Users.module.scss
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/components/table/Table.module.scss
  src/dashboard/src/styles/_colors.scss
Labels: enhancement

#107 HOSTSD-246 Fix Data Service
  src/api/Areas/Services/Controllers/FileSystemItemController.cs
  src/data-service/DataService.cs
  src/data-service/Helpers/HsbApiService.cs
  src/data-service/Helpers/IHsbApiService.cs
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/IFileSystemItemService.cs
  src/libs/models/Filters/FileSystemItemFilter.cs
Labels: bug

#108 HOSTSD-246 Fix Data Service
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/charts/storageTrends/hooks/index.ts
  src/dashboard/src/components/charts/storageTrends/hooks/useStorageTrendsData.ts
  src/data-service/DataService.cs
  src/libs/dal/Services/ServerItemService.cs
  src/libs/models/ServerItemModel.cs
Labels: bug

#109 HOSTSD-246 Enhance Data Service
  src/api/Areas/Services/Controllers/OrganizationController.cs
  src/data-service/Config/ServiceOptions.cs
  src/data-service/DataService.cs
  src/data-service/Helpers/HsbApiService.cs
  src/data-service/Helpers/IHsbApiService.cs
  src/libs/dal/Services/IOrganizationService.cs
  src/libs/dal/Services/OrganizationService.cs
Labels: enhancement

#110 HOSTSD-304 Add email
  HSB.sln
  devops/kustomize/base/data-service/config-map.yaml
  devops/kustomize/base/data-service/cron-job.yaml
  devops/kustomize/base/data-service/network-policy.yaml
  devops/kustomize/base/tekton/tasks/data-service.yaml
  devops/kustomize/overlays/dev/data-service/kustomization.yaml
  devops/kustomize/overlays/secrets/README.md
  devops/kustomize/overlays/secrets/dev/kustomization.yaml
  devops/kustomize/overlays/secrets/test/kustomization.yaml
  devops/kustomize/overlays/test/data-service/kustomization.yaml
  scripts/oc.sh
  scripts/setup.sh
  src/data-service/Config/ServiceOptions.cs
  src/data-service/DataService.cs
  src/data-service/HSB.DataService.csproj
  src/data-service/ServiceManager.cs
  src/data-service/appsettings.json
  src/libs/ches/ChesService.cs
  src/libs/ches/Configuration/ChesOptions.cs
  src/libs/ches/Exceptions/ChesException.cs
  src/libs/ches/Extensions/ServiceCollectionExtensions.cs
  src/libs/ches/HSB.Ches.csproj
  src/libs/ches/IChesService.cs
  src/libs/ches/Models/AttachmentModel.cs
  src/libs/ches/Models/EmailBodyTypes.cs
  src/libs/ches/Models/EmailContextModel.cs
  src/libs/ches/Models/EmailEncodings.cs
  src/libs/ches/Models/EmailMergeModel.cs
  src/libs/ches/Models/EmailModel.cs
  src/libs/ches/Models/EmailPriorities.cs
  src/libs/ches/Models/EmailResponseModel.cs
  src/libs/ches/Models/ErrorModel.cs
  src/libs/ches/Models/ErrorResponseModel.cs
  src/libs/ches/Models/IAttachment.cs
  src/libs/ches/Models/IEmail.cs
  src/libs/ches/Models/IEmailContext.cs
  src/libs/ches/Models/IEmailMerge.cs
  src/libs/ches/Models/MessageResponseModel.cs
  src/libs/ches/Models/StatusHistoryResponseModel.cs
  src/libs/ches/Models/StatusModel.cs
  src/libs/ches/Models/StatusResponseModel.cs
  src/libs/core/Converters/BooleanConverter.cs
  src/libs/core/Converters/DictionaryJsonConverter.cs
  src/libs/core/Converters/EnumValueJsonConverter.cs
  src/libs/core/Converters/Int32ToStringJsonConverter.cs
  src/libs/core/Converters/MicrosecondEpochJsonConverter.cs
  src/libs/core/Json/EnumValueAttribute.cs
Labels: enhancement

#111 HOSTSD-254 Add preapproved user
  EMERALD.md
  src/api/Keycloak/CssHelper.cs
  src/dashboard/src/app/api/auth/authOptions.ts
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/login/page.tsx
  src/dashboard/src/app/page.tsx
  src/dashboard/src/app/welcome/Welcome.module.scss
  src/dashboard/src/app/welcome/page.tsx
  src/dashboard/src/components/auth/AuthState.tsx
  src/dashboard/src/components/loadingAnimation/LoadingAnimation.module.scss
  src/dashboard/src/store/useAppStore.ts
  src/libs/dal/Extensions/ServiceCollectionExtensions.cs
  src/libs/dal/Services/UserService.cs
Labels: bug, enhancement

#112 HOSTSD-307 - Fixing server table layout
  src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
  src/dashboard/src/components/charts/allocationTable/TableRow.tsx
  src/dashboard/src/components/spinner/Spinner.module.scss
Labels: bug

#113 Fix user admin
  README.md
  src/api/Areas/Admin/Controllers/UserController.cs
  src/api/Keycloak/CssHelper.cs
  src/dashboard/src/components/auth/AuthState.tsx
Labels: bug

#115 HOSTSD-312 - updating request access email and storage trends disclaimer
  src/dashboard/src/app/hsb/admin/users/AddNewUserRow.tsx
  src/dashboard/src/app/hsb/admin/users/Users.module.scss
  src/dashboard/src/app/login/page.tsx
  src/dashboard/src/app/welcome/page.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
  src/dashboard/src/components/charts/line/LineChart.module.scss
  src/dashboard/src/components/charts/line/LineChart.tsx
Labels: enhancement

#116 HOSTSD-254 Disable user account
  src/dashboard/src/app/not-authorized/NotAuthorized.module.scss
  src/dashboard/src/app/not-authorized/page.tsx
  src/dashboard/src/components/auth/AuthState.tsx
  src/dashboard/src/components/header/Header.tsx
Labels: enhancement

#118 HOSTSD-217, 262, 314 - Adding responsive styles for filter
  src/dashboard/src/app/login/Login.module.scss
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
  src/dashboard/src/components/charts/line/LineChart.module.scss
  src/dashboard/src/components/charts/line/LineChart.tsx
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.module.scss
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/filter/Filter.module.scss
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/header/Header.module.scss
  src/dashboard/src/styles/_variables.scss
Labels: enhancement

#119 HOSTSD-237 Export to Excel
  src/api/Areas/Dashboard/Controllers/ServerItemController.cs
  src/api/Helpers/IXlsExporter.cs
  src/api/Helpers/XlsExporter.cs
  src/dashboard/src/app/api/dashboard/server-items/history/export/route.ts
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/bar/allocationByOS/AllocationByOS.tsx
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
  src/dashboard/src/components/charts/line/LineChart.tsx
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/hooks/api/interfaces/IServerItemFilter.ts
  src/dashboard/src/hooks/api/useApiServerItems.ts
  src/dashboard/src/hooks/index.ts
  src/dashboard/src/hooks/useDownload.ts
  src/dashboard/src/styles/_globals.scss
  src/libs/dal/Services/IServerHistoryItemService.cs
  src/libs/dal/Services/IServerItemService.cs
  src/libs/dal/Services/ServerHistoryItemService.cs
  src/libs/dal/Services/ServerItemService.cs
  src/libs/models/Filters/ServerItemFilter.cs
Labels: enhancement

#120 HOSTSD-315 - adding toast messages for excel export functions
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/dashboard/Dashboard.tsx
Labels: enhancement

#121 HOSTSD-276 Storage Trend Size Type
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/charts/storageTrends/hooks/useStorageTrendsData.ts
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/utils/convertToStorageSize.ts
Labels: enhancement

#122 HOSTSD-295 Fix dashboard and filter
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/filter/FilteredOrganizations.tsx
  src/dashboard/src/components/filter/FilteredTenants.tsx
Labels: bug

#123 HOSTSD-300 Update filter select
  src/dashboard/src/app/style-guide/page.tsx
  src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
  src/dashboard/src/components/filter/FilteredOrganizations.tsx
  src/dashboard/src/components/filter/FilteredServerItems.tsx
  src/dashboard/src/components/filter/FilteredTenants.tsx
Labels: enhancement

#124 HOSTSD-317 - fixing dropdown covered by loading overlay bug
  src/dashboard/src/components/filter/Filter.module.scss
  src/dashboard/src/components/forms/select/Select.module.scss
Labels: bug

#125 HOSTSD-310 Update Data Service
  src/data-service/Helpers/ServiceNowApiService.cs
Labels: enhancement

#126 HOSTSD-240 Keep removed servers
  src/api/Areas/Dashboard/Controllers/FileSystemItemController.cs
  src/api/Areas/Dashboard/Controllers/OperatingSystemItemController.cs
  src/api/Areas/Dashboard/Controllers/OrganizationController.cs
  src/api/Areas/Dashboard/Controllers/ServerItemController.cs
  src/api/Areas/Dashboard/Controllers/TenantController.cs
  src/data-service/DataService.cs
  src/libs/dal/Migrations/1.0.3/Down/PostDown/01-FindFileSystemHistoryItemsByMonth.sql
  src/libs/dal/Migrations/1.0.3/Down/PostDown/01-FindFileSystemHistoryItemsByMonthForUser.sql
  src/libs/dal/Migrations/1.0.3/Down/PostDown/01-FindServerHistoryItemsByMonth.sql
  src/libs/dal/Migrations/1.0.3/Down/PostDown/01-FindServerHistoryItemsByMonthForUser.sql
  src/libs/dal/Migrations/1.0.3/Up/PostUp/01-FindFileSystemHistoryItemsByMonth.sql
  src/libs/dal/Migrations/1.0.3/Up/PostUp/01-FindFileSystemHistoryItemsByMonthForUser.sql
  src/libs/dal/Migrations/1.0.3/Up/PostUp/01-FindServerHistoryItemsByMonth.sql
  src/libs/dal/Migrations/1.0.3/Up/PostUp/01-FindServerHistoryItemsByMonthForUser.sql
  src/libs/dal/Migrations/20240327151737_1.0.3.Designer.cs
  src/libs/dal/Migrations/20240327151737_1.0.3.cs
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/ServerItemService.cs
Labels: enhancement, data-service

#128 HOSTSD-320 Fix filter dropdown
  README.md
  src/dashboard/src/components/forms/select/FilterDropdown.tsx
Labels: bug

#129 HOSTSD-319 Fix Drive Space Loading
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/hooks/filter/useFilteredFileSystemItems.ts
  src/dashboard/src/hooks/filter/useFilteredOperatingSystemItems.ts
  src/dashboard/src/hooks/filter/useFilteredOrganizations.ts
  src/dashboard/src/hooks/filter/useFilteredServerItems.ts
  src/dashboard/src/hooks/filter/useFilteredTenants.ts
  src/dashboard/src/store/useFilteredStore.ts
Labels: bug

#130 Fix Data Service email
  devops/kustomize/base/data-service/config-map.yaml
  devops/kustomize/base/data-service/cron-job.yaml
  devops/kustomize/overlays/dev/data-service/kustomization.yaml
  devops/kustomize/overlays/prod/data-service/kustomization.yaml
  devops/kustomize/overlays/test/data-service/kustomization.yaml
  src/data-service/Config/ServiceOptions.cs
  src/data-service/DataService.cs
Labels: bug

#131 Fix Data Service
  src/libs/dal/Services/ServerItemService.cs
Labels: bug
