Repository bcgov/hsb-dashboard, pull requests merged in 2024-01, with the labels that each got.

#37 HOSTSD-172, 173 - Adding Storage Trends and Allocation by Storage Volume charts
  src/dashboard/package-lock.json
  src/dashboard/package.json
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/app/style-guide/StyleGuide.module.scss
  src/dashboard/src/app/style-guide/page.tsx
  src/dashboard/src/components/charts/allOrgDonut/AllOrgDonutChart.module.scss
  src/dashboard/src/components/charts/allOrgDonut/AllOrgDonutChart.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/AllocationByStorageVolumeChart.module.scss
  src/dashboard/src/components/charts/allocationByStorageVolume/AllocationByStorageVolumeChart.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/BarChart.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/OrganizationsChart.module.scss
  src/dashboard/src/components/charts/allocationByStorageVolume/OrganizationsChart.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/index.ts
  src/dashboard/src/components/charts/bar/BarChart.tsx
  src/dashboard/src/components/charts/bar/index.ts
  src/dashboard/src/components/charts/index.ts
  src/dashboard/src/components/charts/line/LineChart.tsx
  src/dashboard/src/components/charts/line/index.ts
  src/dashboard/src/components/charts/lineChart/Chart.module.scss
  src/dashboard/src/components/charts/lineChart/Chart.tsx
  src/dashboard/src/components/charts/lineChart/index.ts
  src/dashboard/src/components/charts/pie/PieChart.tsx
  src/dashboard/src/components/charts/pie/index.ts
  src/dashboard/src/components/header/Header.module.scss
  src/dashboard/src/styles/_globals.scss
  src/dashboard/src/styles/_variables.scss
  src/dashboard/src/styles/globals.scss
Labels: enhancement

#38 HOSTSD-189 Add file system item endpoints
  devops/kustomize/base/api/deploy.yaml
  devops/kustomize/base/tekton/taskruns/buildah.yaml
  src/api/Areas/Dashboard/Controllers/FileSystemItemController.cs
  src/api/Areas/Dashboard/Controllers/ServerItemController.cs
  src/dashboard/src/app/api/dashboard/file-system-items/history/route.ts
  src/dashboard/src/app/api/dashboard/server-items/history/route.ts
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/OrganizationsChart.tsx
  src/dashboard/src/components/charts/index.ts
  src/dashboard/src/components/charts/lineChart/Chart.tsx
  src/dashboard/src/components/charts/lineChart/LineChart.module.scss
  src/dashboard/src/components/charts/lineChart/LineChart.tsx
  src/dashboard/src/components/charts/lineChart/defaultChartOptions.ts
  src/dashboard/src/components/charts/lineChart/index.ts
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/charts/storageTrends/defaultData.ts
  src/dashboard/src/components/charts/storageTrends/generateData.ts
  src/dashboard/src/components/charts/storageTrends/index.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/forms/select/Select.tsx
  src/dashboard/src/hooks/api/interfaces/IFileSystemHistoryItemFilter.ts
  src/dashboard/src/hooks/api/interfaces/IServerHistoryItemFilter.ts
  src/dashboard/src/hooks/api/interfaces/index.ts
  src/dashboard/src/hooks/api/useApiFileSystemItems.ts
  src/dashboard/src/hooks/api/useApiServerItems.ts
  src/libs/Dockerfile
  src/libs/core/Extensions/DictionaryExtensions.cs
  src/libs/dal/HSBContext.cs
  src/libs/dal/Migrations/0.0.0/Up/PostUp/00-DataSync.sql
  src/libs/dal/Migrations/0.0.0/Up/PostUp/04-FindFileSystemHistoryItemsByMonth.sql
  src/libs/dal/Migrations/0.0.0/Up/PostUp/04-FindServerHistoryItemsByMonth.sql
  src/libs/dal/Services/FileSystemHistoryItemService.cs
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/IFileSystemHistoryItemService.cs
  src/libs/dal/Services/IFileSystemItemService.cs
  src/libs/dal/Services/IServerHistoryItemService.cs
  src/libs/dal/Services/ServerHistoryItemService.cs
  src/libs/models/Filters/FileSystemHistoryItemFilter.cs
  src/libs/models/Filters/ServerHistoryItemFilter.cs
Labels: enhancement

#40 HOSTSD-199 Add storage trends chart
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/components/buttons/Button.module.scss
  src/dashboard/src/components/buttons/Button.tsx
  src/dashboard/src/components/charts/allOrgDonut/AllOrgDonutChart.tsx
  src/dashboard/src/components/charts/allOrgDonut/updateData.ts
  src/dashboard/src/components/charts/allOrgDonut/useDonutChart.ts
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/charts/storageTrends/generateData.ts
  src/dashboard/src/components/charts/storageTrends/useStorageTrends.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/forms/select/Select.module.scss
  src/dashboard/src/components/forms/select/Select.tsx
  src/dashboard/src/components/spinner/Spinner.module.scss
  src/dashboard/src/components/spinner/Spinner.tsx
  src/dashboard/src/hooks/api/interfaces/IFileSystemHistoryItemModel.ts
  src/dashboard/src/hooks/api/interfaces/IServerHistoryItemModel.ts
  src/dashboard/src/hooks/api/interfaces/IServerItemModel.ts
  src/dashboard/src/hooks/dashboard/index.ts
  src/dashboard/src/hooks/dashboard/useDashboardFileSystemHistoryItems.ts
  src/dashboard/src/hooks/dashboard/useDashboardServerHistoryItems.ts
  src/dashboard/src/hooks/filter/useFilteredServerItems.ts
  src/dashboard/src/store/index.ts
  src/dashboard/src/store/useDashboard.ts
  src/dashboard/src/store/useFiltered.ts
  src/dashboard/src/utils/calcMonthsBetween.ts
  src/dashboard/src/utils/convertToStorageSize.ts
  src/dashboard/src/utils/index.ts
  src/data-service/DataService.cs
  src/data-service/Helpers/HsbApiService.cs
  src/data-service/Helpers/IHsbApiService.cs
  src/libs/dal/Configuration/FileSystemHistoryItemConfiguration.cs
  src/libs/dal/Configuration/ServerHistoryItemConfiguration.cs
  src/libs/dal/Configuration/ServerItemConfiguration.cs
  src/libs/dal/Migrations/0.0.0/Down/PreDown/00-FindFileSystemHistoryItemsByMonth.sql
  src/libs/dal/Migrations/0.0.0/Down/PreDown/00-FindServerHistoryItemsByMonth.sql
  src/libs/dal/Migrations/0.0.0/Up/PostUp/04-FindServerHistoryItemsByMonth.sql
  src/libs/dal/Migrations/20240104163357_0.0.0.Designer.cs
  src/libs/dal/Migrations/20240104163357_0.0.0.cs
  src/libs/dal/Migrations/HSBContextModelSnapshot.cs
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/ServerItemService.cs
  src/libs/entities/FileSystemHistoryItem.cs
  src/libs/entities/FileSystemItem.cs
  src/libs/entities/ServerHistoryItem.cs
  src/libs/entities/ServerItem.cs
  src/libs/models/FileSystemHistoryItemModel.cs
  src/libs/models/ServerHistoryItemModel.cs
Labels: enhancement

#41 HOSTSD-119 Add allocation by storage volume - all organizations
  devops/kustomize/base/api/deploy.yaml
  src/dashboard/src/components/charts/allocationByStorageVolume/AllocationByStorageVolume.module.scss
  src/dashboard/src/components/charts/allocationByStorageVolume/AllocationByStorageVolume.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/BarChart.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/IOrganizationStorageModel.ts
  src/dashboard/src/components/charts/allocationByStorageVolume/OrganizationsChart.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/PercentageLines.tsx
  src/dashboard/src/components/charts/allocationByStorageVolume/calcOrganizationStorage.ts
  src/dashboard/src/components/charts/allocationByStorageVolume/index.ts
  src/dashboard/src/components/charts/allocationByStorageVolume/sortOptions.ts
  src/dashboard/src/components/forms/interfaces/IOption.ts
  src/dashboard/src/utils/convertToStorageSize.ts
Labels: enhancement

#43 HOSTSD-201 Add total storage chart
  src/dashboard/src/components/charts/doughnut/IDoughnutStats.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/defaultData.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/generateDoughnutChart.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/index.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/useAllOrganizationsDoughnutChart.ts
  src/dashboard/src/components/charts/doughnut/index.ts
  src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.tsx
  src/dashboard/src/components/charts/doughnut/totalStorage/defaultData.ts
  src/dashboard/src/components/charts/doughnut/totalStorage/hooks/generateDoughnutChart.ts
  src/dashboard/src/components/charts/doughnut/totalStorage/hooks/index.ts
  src/dashboard/src/components/charts/doughnut/totalStorage/hooks/useTotalStorageDoughnutChart.ts
  src/dashboard/src/components/charts/hooks/index.ts
  src/dashboard/src/components/charts/index.ts
Labels: enhancement

#44 HOSTSD-177 - Adding Server Allocation Table
  src/dashboard/package-lock.json
  src/dashboard/package.json
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/allocationTable/Dropdown.tsx
  src/dashboard/src/components/charts/allocationTable/TableRow.tsx
  src/dashboard/src/components/charts/allocationTable/defaultData.ts
  src/dashboard/src/components/charts/allocationTable/index.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
  src/dashboard/src/components/charts/index.ts
  src/dashboard/src/components/charts/unusedSpace/UnusedSpaceChart.module.scss
  src/dashboard/src/styles/_globals.scss
Labels: enhancement

#46 HOSTSD-204 Add allocation by storage for OS
  keycloak/config/realm-export.json
  src/dashboard/src/app/client/dashboard/page.tsx
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/components/buttons/Button.tsx
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/allocationTable/Dropdown.tsx
  src/dashboard/src/components/charts/allocationTable/ITableRowData.ts
  src/dashboard/src/components/charts/allocationTable/TableRow.tsx
  src/dashboard/src/components/charts/allocationTable/constants/OperatingSystems.ts
  src/dashboard/src/components/charts/allocationTable/constants/index.ts
  src/dashboard/src/components/charts/allocationTable/defaultData.ts
  src/dashboard/src/components/charts/allocationTable/hooks/index.ts
  src/dashboard/src/components/charts/allocationTable/hooks/useAllocationByOS.ts
  src/dashboard/src/components/charts/allocationTable/utils/getColumns.ts
  src/dashboard/src/components/charts/allocationTable/utils/getLabel.ts
  src/dashboard/src/components/charts/allocationTable/utils/index.ts
  src/dashboard/src/components/charts/bar/allocationByOS/AllocationByOS.tsx
  src/dashboard/src/components/charts/bar/allocationByOS/defaultData.ts
  src/dashboard/src/components/charts/bar/allocationByOS/utils/groupByOS.ts
  src/dashboard/src/components/charts/bar/allocationByOS/utils/index.ts
  src/dashboard/src/components/charts/bar/smallBar/BarRow.tsx
  src/dashboard/src/components/charts/bar/smallBar/IBarChartRowData.ts
  src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/useAllOrganizationsDoughnutChart.ts
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/charts/storageTrends/useStorageTrends.ts
  src/dashboard/src/components/forms/text/Text.tsx
  src/dashboard/src/components/table/ITableFooterProps.ts
  src/dashboard/src/components/table/ITableHeaderProps.ts
  src/dashboard/src/components/table/ITableRowProps.ts
  src/dashboard/src/components/table/Table.tsx
  src/libs/core/HSB.Core.csproj
  src/libs/dal/HSBContext.cs
  src/libs/dal/Migrations/0.0.0/Up/PostUp/04-FindFileSystemHistoryItemsByMonthForUser.sql
  src/libs/dal/Migrations/0.0.0/Up/PostUp/04-FindServerHistoryItemsByMonthForUser.sql
  src/libs/dal/Services/FileSystemHistoryItemService.cs
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/IFileSystemHistoryItemService.cs
  src/libs/dal/Services/OperatingSystemItemService.cs
  src/libs/dal/Services/OrganizationService.cs
  src/libs/dal/Services/ServerHistoryItemService.cs
  src/libs/dal/Services/ServerItemService.cs
Labels: enhancement

#47 Rollback dependency version
  src/libs/core/HSB.Core.csproj
Labels: bug

#48 HOSTSD-182 - Adding segmented bar chart for drive storage
  database/Dockerfile
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/components/charts/bar/index.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.module.scss
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/defaultData.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/index.ts
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
  src/data-service/Dockerfile
Labels: enhancement

#49 A few fixes for client users
  src/api/Areas/Dashboard/Controllers/OperatingSystemItemController.cs
  src/api/Areas/Dashboard/Controllers/OrganizationController.cs
  src/api/Areas/Dashboard/Controllers/ServerItemController.cs
  src/api/Areas/Dashboard/Controllers/TenantController.cs
  src/api/Program.cs
  src/libs/dal/Services/IOrganizationService.cs
  src/libs/dal/Services/OrganizationService.cs
  src/libs/dal/Services/TenantService.cs
  src/libs/models/Filters/OrganizationFilter.cs
Labels: bug

#50 HOSTSD-203 Add storage trends by drive
  src/api/Areas/Dashboard/Controllers/FileSystemItemController.cs
  src/dashboard/src/app/client/dashboard/page.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/IVolumeData.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.module.scss
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/defaultData.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/defaultOptions.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/useStorageTrends.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/utils/extractVolumeName.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/utils/index.ts
  src/dashboard/src/components/charts/hooks/index.ts
  src/dashboard/src/components/charts/hooks/useStorageHistoryDateRange.ts
  src/dashboard/src/components/charts/storageTrends/useStorageTrends.ts
  src/dashboard/src/hooks/dashboard/useDashboardFileSystemHistoryItems.ts
  src/libs/dal/Migrations/0.0.0/Up/PostUp/04-FindFileSystemHistoryItemsByMonth.sql
Labels: enhancement

#51 Fix bug
  src/dashboard/src/components/charts/bar/segmentedBarChart/useStorageTrends.ts
Labels: bug

#52 HOSTSD-225 - HSB Admin - Users Admin page
  src/dashboard/src/app/hsb/admin/users/Users.module.scss
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/components/forms/select/Select.module.scss
  src/dashboard/src/components/forms/select/Select.tsx
  src/dashboard/src/components/header/Header.module.scss
  src/dashboard/src/components/header/Header.tsx
  src/dashboard/src/components/info/Info.module.scss
  src/dashboard/src/components/sheet/Sheet.module.scss
  src/dashboard/src/components/table/Table.module.scss
Labels: enhancement

#53 HOSTSD-227 HSB user pages
  src/dashboard/src/app/client/admin/organizations/[id]/page.tsx
  src/dashboard/src/app/client/admin/organizations/page.tsx
  src/dashboard/src/app/client/admin/page.tsx
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/client/dashboard/[id]/page.tsx
  src/dashboard/src/app/client/dashboard/page.tsx
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/admin/groups/[id]/page.tsx
  src/dashboard/src/app/hsb/admin/groups/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/hsb/dashboard/Page.module.scss
  src/dashboard/src/app/hsb/dashboard/[id]/page.tsx
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/allocationTable/constants/OperatingSystems.ts
  src/dashboard/src/components/charts/allocationTable/constants/index.ts
  src/dashboard/src/components/charts/allocationTable/hooks/useAllocationByOS.ts
  src/dashboard/src/components/charts/allocationTable/utils/getLabel.ts
  src/dashboard/src/components/charts/bar/allocationByOS/AllocationByOS.tsx
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx
  src/dashboard/src/components/charts/bar/allocationByVolume/AllocationByVolume.tsx
  src/dashboard/src/components/charts/bar/allocationByVolume/defaultData.ts
  src/dashboard/src/components/charts/bar/allocationByVolume/index.ts
  src/dashboard/src/components/charts/bar/index.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/useAllOrganizationsDoughnutChart.ts
  src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.tsx
  src/dashboard/src/components/charts/doughnut/totalStorage/hooks/useTotalStorageDoughnutChart.ts
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/dashboard/index.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/header/Header.tsx
  src/dashboard/src/components/index.ts
  src/dashboard/src/hooks/dashboard/index.ts
  src/dashboard/src/hooks/dashboard/useDashboardOperatingSystemItems.ts
  src/dashboard/src/hooks/dashboard/useDashboardOrganizations.ts
  src/dashboard/src/hooks/dashboard/useDashboardServerItems.ts
  src/dashboard/src/hooks/dashboard/useDashboardTenants.ts
  src/dashboard/src/hooks/filter/useFilteredOperatingSystemItems.ts
  src/dashboard/src/hooks/index.ts
  src/dashboard/src/hooks/useAuth.ts
  src/dashboard/src/hooks/useSecureRoute.ts
  src/dashboard/src/store/useDashboard.ts
Labels: enhancement

#54 HOSTSD-229 Client pages
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/allocationTable/ITableRowData.ts
  src/dashboard/src/components/charts/allocationTable/TableRow.tsx
  src/dashboard/src/components/charts/allocationTable/defaultData.ts
  src/dashboard/src/components/charts/allocationTable/hooks/useAllocationByOS.ts
  src/dashboard/src/components/charts/bar/allocationByOS/AllocationByOS.tsx
  src/dashboard/src/components/charts/bar/allocationByOS/defaultData.ts
  src/dashboard/src/components/charts/bar/allocationByOS/utils/groupByOS.ts
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.module.scss
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/BarChart.tsx
  src/dashboard/src/components/charts/bar/allocationByVolume/AllocationByVolume.tsx
  src/dashboard/src/components/charts/bar/allocationByVolume/defaultData.ts
  src/dashboard/src/components/charts/bar/smallBar/BarRow.tsx
  src/dashboard/src/components/charts/bar/smallBar/IBarChartData.ts
  src/dashboard/src/components/charts/bar/smallBar/IBarChartRowData.ts
  src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.module.scss
  src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.tsx
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/dashboard/index.ts
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/components/filter/Filter.tsx
Labels: enhancement

#55 HOSTSD-209 Fix all servers and auth bugs
  src/dashboard/src/app/client/admin/page.tsx
  src/dashboard/src/app/client/admin/users/[id]/page.tsx
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/client/dashboard/page.tsx
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/[id]/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/page.tsx
  src/dashboard/src/app/hsb/admin/users/[id]/page.tsx
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/hsb/dashboard/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/charts/bar/allocationByVolume/AllocationByVolume.tsx
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/hooks/index.ts
  src/dashboard/src/hooks/useSecureRoute.ts
Labels: bug, enhancement

#57 HOSTSD-222, 225, 184 - Admin Panels
  src/dashboard/public/images/trash-icon.png
  src/dashboard/public/images/trash-icon.svg
  src/dashboard/src/app/client/admin/users/ClientAdmin.module.scss
  src/dashboard/src/app/client/admin/users/IUserForm.ts
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/IUserForm.ts
  src/dashboard/src/app/hsb/admin/organizations/Organizations.module.scss
  src/dashboard/src/app/hsb/admin/organizations/[id]/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/users/Users.module.scss
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/style-guide/page.tsx
  src/dashboard/src/components/forms/select/Select.module.scss
  src/dashboard/src/components/header/Header.module.scss
  src/dashboard/src/components/header/Header.tsx
  src/dashboard/src/styles/_globals.scss
Labels: enhancement

#58 HOSTSD-209 Fix URL navigation
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/filter/hooks/useUrlParamsUpdateKey.ts
  src/libs/dal/Services/ServerItemService.cs
Labels: bug

#59 Fixes for filter
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/filter/Filter.tsx
  src/libs/models/Filters/ServerHistoryItemFilter.cs
  src/libs/models/Filters/ServerItemFilter.cs
Labels: bug

#60 HOSTSD-226, 183 - Added admin confirmation popup and fixed server page styling
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/allocationTable/TableRow.tsx
  src/dashboard/src/components/confirmPopup/ConfirmPopup.module.scss
  src/dashboard/src/components/confirmPopup/ConfirmPopup.tsx
  src/dashboard/src/components/confirmPopup/index.ts
  src/dashboard/src/components/header/Header.tsx
  src/dashboard/src/components/index.ts
Labels: enhancement

#61 HOSTSD-228 Add user admin
  src/api/Areas/Admin/Controllers/OrganizationController.cs
  src/api/Areas/Admin/Controllers/TenantController.cs
  src/api/Areas/Admin/Controllers/UserController.cs
  src/api/Areas/Dashboard/Controllers/OrganizationController.cs
  src/api/Areas/Dashboard/Controllers/TenantController.cs
  src/api/Areas/Services/Controllers/OrganizationController.cs
  src/api/Areas/Services/Controllers/TenantController.cs
  src/dashboard/src/app/api/admin/users/[id]/route.ts
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/IOrganizationForm.ts
  src/dashboard/src/app/hsb/admin/organizations/IUserForm.ts
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/utils/index.ts
  src/dashboard/src/app/hsb/admin/organizations/utils/searchOrganizations.ts
  src/dashboard/src/app/hsb/admin/page.tsx
  src/dashboard/src/app/hsb/admin/users/UserDialog.tsx
  src/dashboard/src/app/hsb/admin/users/Users.module.scss
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/hsb/admin/users/utils/index.ts
  src/dashboard/src/app/hsb/admin/users/utils/searchUsers.ts
  src/dashboard/src/components/dialog/Dialog.module.scss
  src/dashboard/src/components/dialog/Dialog.tsx
  src/dashboard/src/components/dialog/index.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/header/Header.tsx
  src/dashboard/src/components/header/Message.tsx
  src/dashboard/src/components/index.ts
  src/dashboard/src/hooks/api/admin/index.ts
  src/dashboard/src/hooks/api/admin/useApiOrganizations.ts
  src/dashboard/src/hooks/api/admin/useApiUsers.ts
  src/dashboard/src/hooks/api/interfaces/IOrganizationFilter.ts
  src/dashboard/src/hooks/api/interfaces/ITenantFilter.ts
  src/dashboard/src/hooks/api/interfaces/IUserFilter.ts
  src/dashboard/src/hooks/api/interfaces/IUserModel.ts
  src/dashboard/src/hooks/api/useApiOrganizations.ts
  src/dashboard/src/hooks/data/useOrganizations.ts
  src/dashboard/src/hooks/data/useUsers.ts
  src/dashboard/src/hooks/filter/useFilteredOrganizations.ts
  src/dashboard/src/hooks/filter/useFilteredTenants.ts
  src/libs/core/Models/ErrorResponseModel.cs
  src/libs/dal/Services/FileSystemHistoryItemService.cs
  src/libs/dal/Services/FileSystemItemService.cs
  src/libs/dal/Services/IOrganizationService.cs
  src/libs/dal/Services/ITenantService.cs
  src/libs/dal/Services/IUserService.cs
  src/libs/dal/Services/OperatingSystemItemService.cs
  src/libs/dal/Services/OrganizationService.cs
  src/libs/dal/Services/ServerHistoryItemService.cs
  src/libs/dal/Services/ServerItemService.cs
  src/libs/dal/Services/TenantService.cs
  src/libs/dal/Services/UserService.cs
  src/libs/models/Filters/OrganizationFilter.cs
  src/libs/models/Filters/TenantFilter.cs
  src/libs/models/Filters/UserFilter.cs
  src/libs/models/GroupModel.cs
  src/libs/models/OrganizationModel.cs
  src/libs/models/TenantModel.cs
  src/libs/models/UserModel.cs
Labels: enhancement

#62 HOSTSD-242, 241 - Moving date range picker to individual charts
  src/dashboard/public/images/reset-icon.png
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.module.scss
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.module.scss
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.module.scss
  src/dashboard/src/components/charts/line/LineChart.module.scss
  src/dashboard/src/components/charts/line/LineChart.tsx
  src/dashboard/src/components/filter/Filter.module.scss
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/forms/date-picker/DateRangePicker.module.scss
  src/dashboard/src/components/forms/date-picker/DateRangePicker.tsx
  src/dashboard/src/components/forms/select/Select.module.scss
  src/dashboard/src/components/header/Header.module.scss
  src/dashboard/src/components/table/Table.module.scss
Labels: enhancement

#63 HOSTSD-228 Add client admin
  src/api/Helpers/AuthorizationHelper.cs
  src/api/Keycloak/CssHelper.cs
  src/api/Keycloak/IKeycloakHelper.cs
  src/api/Keycloak/KeycloakHelper.cs
  src/api/Models/Auth/OrganizationModel.cs
  src/api/Models/Auth/PrincipalModel.cs
  src/api/Models/Auth/TenantModel.cs
  src/dashboard/src/app/client/admin/page.tsx
  src/dashboard/src/app/client/admin/users/[id]/page.tsx
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/client/admin/users/utils/getOrganizationOptions.ts
  src/dashboard/src/app/client/admin/users/utils/getTenantOptions.ts
  src/dashboard/src/app/client/admin/users/utils/index.ts
  src/dashboard/src/app/client/admin/users/utils/searchUsers.ts
  src/dashboard/src/app/hsb/admin/organizations/[id]/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/utils/index.ts
  src/dashboard/src/app/hsb/admin/users/page.tsx
  src/dashboard/src/app/hsb/admin/users/utils/index.ts
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
  src/dashboard/src/components/filter/FilteredOrganizations.tsx
  src/dashboard/src/components/filter/FilteredServerItems.tsx
  src/dashboard/src/components/filter/FilteredTenants.tsx
  src/dashboard/src/hooks/api/interfaces/auth/IOrganizationModel.ts
  src/dashboard/src/hooks/api/interfaces/auth/ITenantModel.ts
  src/dashboard/src/hooks/api/interfaces/auth/IUserInfoModel.ts
  src/dashboard/src/hooks/api/interfaces/auth/index.ts
  src/dashboard/src/hooks/api/interfaces/index.ts
  src/dashboard/src/hooks/data/useUsers.ts
  src/dashboard/src/hooks/filter/useFilteredOrganizations.ts
  src/dashboard/src/store/useApp.ts
  src/dashboard/src/utils/getOrganizationOptions.ts
  src/dashboard/src/utils/getUserOptions.ts
  src/dashboard/src/utils/index.ts
  src/dashboard/src/utils/searchOrganizations.ts
  src/dashboard/src/utils/searchUsers.ts
  src/libs/dal/Services/IUserService.cs
  src/libs/dal/Services/UserService.cs
Labels: enhancement

#64 HOSTSD-235 Deploy Data Service
  .github/workflows/ci-cd-dev.yml
  .github/workflows/dotnet.yml
  devops/kustomize/base/api/deploy.yaml
  devops/kustomize/base/data-service/cron-job.yaml
  devops/kustomize/base/data-service/kustomization.yaml
  devops/kustomize/tools/build/data-service.yaml
  src/dashboard/src/components/filter/FilteredTenants.tsx
Labels: enhancement

#66 HOSTSD-235 Update CI/CD
  .github/workflows/ci-cd-dev.yml
  src/data-service/entrypoint.sh
Labels: enhancement, data-service

#67 HOSTSD-243 - adding loading component to all charts
  src/dashboard/src/components/buttons/Button.module.scss
  src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/bar/allocationByOS/AllocationByOS.tsx
  src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx
  src/dashboard/src/components/charts/bar/allocationByVolume/AllocationByVolume.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.tsx
  src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
  src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.tsx
  src/dashboard/src/components/charts/index.ts
  src/dashboard/src/components/charts/line/LineChart.tsx
  src/dashboard/src/components/charts/loadingAnimation/LoadingAnimation.module.scss
  src/dashboard/src/components/charts/loadingAnimation/LoadingAnimation.tsx
  src/dashboard/src/components/charts/loadingAnimation/index.ts
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/forms/select/Select.module.scss
Labels: enhancement

#69 HOSTSD-258 Implement Date Pickers
  devops/kustomize/base/data-service/cron-job.yaml
  src/dashboard/src/app/client/admin/users/page.tsx
  src/dashboard/src/app/client/servers/page.tsx
  src/dashboard/src/app/hsb/admin/organizations/page.tsx
  src/dashboard/src/app/hsb/servers/page.tsx
  src/dashboard/src/components/auth/AuthState.tsx
  src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
  src/dashboard/src/components/charts/allocationTable/hooks/useAllocationByOS.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
  src/dashboard/src/components/charts/bar/segmentedBarChart/hooks/index.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/hooks/useFileSystemHistoryItems.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/useStorageTrends.ts
  src/dashboard/src/components/charts/bar/segmentedBarChart/useStorageTrendsData.ts
  src/dashboard/src/components/charts/hooks/index.ts
  src/dashboard/src/components/charts/index.ts
  src/dashboard/src/components/charts/line/LineChart.module.scss
  src/dashboard/src/components/charts/line/LineChart.tsx
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.module.scss
  src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
  src/dashboard/src/components/charts/storageTrends/hooks/index.ts
  src/dashboard/src/components/charts/storageTrends/hooks/useServerHistoryItems.ts
  src/dashboard/src/components/charts/storageTrends/useStorageTrends.ts
  src/dashboard/src/components/charts/storageTrends/useStorageTrendsData.ts
  src/dashboard/src/components/charts/utils/generateStorageHistoryForDateRange.ts
  src/dashboard/src/components/charts/utils/index.ts
  src/dashboard/src/components/dashboard/Dashboard.tsx
  src/dashboard/src/components/dashboard/useDashboardFilter.ts
  src/dashboard/src/components/filter/Filter.tsx
  src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
  src/dashboard/src/components/filter/FilteredOrganizations.tsx
  src/dashboard/src/components/filter/FilteredServerItems.tsx
  src/dashboard/src/components/filter/FilteredTenants.tsx
  src/dashboard/src/components/filter/hooks/useUrlParamsUpdateKey.ts
  src/dashboard/src/components/forms/date-picker/DateRangePicker.tsx
  src/dashboard/src/components/header/Message.tsx
  src/dashboard/src/hooks/dashboard/index.ts
  src/dashboard/src/hooks/dashboard/useDashboard.ts
  src/dashboard/src/hooks/dashboard/useDashboardOperatingSystemItems.ts
  src/dashboard/src/hooks/dashboard/useDashboardOrganizations.ts
  src/dashboard/src/hooks/dashboard/useDashboardServerItems.ts
  src/dashboard/src/hooks/dashboard/useDashboardTenants.ts
  src/dashboard/src/hooks/data/useGroups.ts
  src/dashboard/src/hooks/data/useOperatingSystemItems.ts
  src/dashboard/src/hooks/data/useOrganizations.ts
  src/dashboard/src/hooks/data/useRoles.ts
  src/dashboard/src/hooks/data/useServerItems.ts
  src/dashboard/src/hooks/data/useTenants.ts
  src/dashboard/src/hooks/data/useUsers.ts
  src/dashboard/src/hooks/filter/useFilteredFileSystemItems.ts
  src/dashboard/src/hooks/filter/useFilteredOperatingSystemItems.ts
  src/dashboard/src/hooks/filter/useFilteredOrganizations.ts
  src/dashboard/src/hooks/filter/useFilteredServerItems.ts
  src/dashboard/src/hooks/filter/useFilteredTenants.ts
  src/dashboard/src/store/index.ts
  src/dashboard/src/store/useAppStore.ts
  src/dashboard/src/store/useDashboardStore.ts
  src/dashboard/src/store/useFilteredStore.ts
  src/dashboard/src/store/useStorageTrendsStore.ts
Labels: enhancement
